# Generated by Django 4.2 on 2025-03-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('date_of_joining', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateField()),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('manager_ticket_status', models.CharField(choices=[('Approved', 'Approved'), ('Request Edit', 'Request Edit'), ('Rejected', 'Rejected'), ('Not Responded', 'Not Responded')], default='Not Responded', max_length=20)),
                ('admin_ticket_status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Not Responded', max_length=20)),
                ('preferred_travel_mode', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Plane', 'Plane'), ('Ship', 'Ship')], default='Bus', max_length=10)),
                ('is_lodging_req', models.BooleanField(default=False)),
                ('purpose_of_travel', models.CharField(max_length=100)),
                ('additional_note_employee', models.TextField(blank=True, null=True)),
                ('additional_request_admin', models.TextField(blank=True, null=True)),
                ('additional_request_manager', models.TextField(blank=True, null=True)),
                ('no_of_submission', models.PositiveIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='travel_app.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='travel_app.manager')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='travel_app.manager'),
        ),
    ]
