# Generated by Django 4.2.17 on 2025-03-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_remove_admin_password_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
