# Generated by Django 4.2.17 on 2025-03-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
